CREATE TABLE IF NOT EXISTS beverage (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT,
	changed TEXT DATETIME CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS drink (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	beverage_id INTEGER,
	amount_ml REAL,
	consumed DATETIME,
	FOREIGN KEY(beverage_id) REFERENCES beverage(id));